### PR TITLE
Added relation to design and refactoring patterns

### LINKED ISSUE #9: Write about software architecture in context of the refactoring
Updates in the source (either as refactorings or bug fixes) are put into context with the overall software architecture and discussed, relating them to design patterns and refactoring patterns.

### PR DESCRIPTION
**Pull request by emilelm96**
Expanded on the report by relating our updates to the overall software architecture and the design and refactoring patterns of the project.

This should close #9

### CODE REVIEW

**Review by Jonagoo — APPROVED** [review]

**Review by francislaus — APPROVED** [review]
Extremely well done!

**Review by Samuelhertzberg — CHANGES_REQUESTED** [review]
"...refactoring consists in merging..." => "...refactoring consists of merging...".
Additionally the first sentence is extremely long.

Also, try to not use 'we' and 'our' as much as possible.
"We wouldn't say that this deviates very much from the overall software..." could be written as:
"This does not deviate from the overall software..." for a more academic style.

**Comment by emilelm96** [comment]
Yes, you're right, the first sentence should be shorter and I should rephrase the text so that there is no we or our, but I don't agree with your first request. There is a (subtle) difference between consist in and consist of, like _bestå i_ and _bestå av_ in Swedish. For [reference](https://english.stackexchange.com/questions/61600/consist-in-vs-consist-of).

**Comment by Samuelhertzberg** [comment]
Alright Mr, dude.

Ya boi,
Illiterate Sam.

**Review by Samuelhertzberg — APPROVED** [review]

**Comment by Samuelhertzberg** [comment]
Alright Mr, dude.

Ya boi,
Illiterate Sam.

**Review by francislaus — APPROVED** [review]

**Pull request merged**
